name: Deploy

on:
  workflow_run:
    workflows:
      - Unit Test
      - UI Test
    branches:
      - master
      - development
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Set production environment variables
        if: github.ref == 'refs/heads/main'
        run: |
          echo "NETLIFY_ALIAS=" >> $GITHUB_ENV
          echo "NETLIFY_PRODUCTION_DEPLOYMENT=true" >> $GITHUB_ENV
          echo "NETLIFY_MESSAGE=Production Deploy from GitHub Actions" >> $GITHUB_ENV

      - name: Set staging environment variables
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "NETLIFY_ALIAS=${{ github.head_ref }}" >> $GITHUB_ENV
          echo "NETLIFY_PRODUCTION_DEPLOYMENT=false" >> $GITHUB_ENV
          echo "NETLIFY_MESSAGE=Staging Deploy from GitHub Actions" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './build'
          production-branch: master
          production-deploy: ${{ secrets.NETLIFY_PRODUCTION_DEPLOYMENT }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: ${{ secrets.NETLIFY_MESSAGE }}
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: ${{ secrets.NETLIFY_ALIAS }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
