name: Unit Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install dependency
        run: yarn

      - name: Run Codebase Lint
        run: yarn codebase:lint

      - name: Run Jest test
        run: yarn test
